sudo: false
language: nix
script: bash .travis/setup.sh && nix-build --argstr date "$(date --date=@$(git log -1 --pretty=%ct) +%F)" --arg doCheck true

deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis/deploy.sh
  on:
    branch: master
    repo: fsi-tue/anfiheft
